### ISSUE TITLE
Erro na documentação "Consultar Modelos Através do Ano"

### ISSUE THREAD

**Issue by redeveiculos** [wgenial/fipe-json#4]
Na documentação para "Consultar Modelos Através do Ano" o endpoint correto é "http://veiculos.fipe.org.br/api/veiculos/ConsultarModelosAtravesDoAno" e não "http://veiculos.fipe.org.br/api/veiculos/ConsultarAnoModelo"

**Comment by giovanigenerali** [comment]
@redeveiculos documentação atualizada, obrigado.
