### ISSUE TITLE
Prestação de serviços

### ISSUE THREAD

**Issue by ignaciob73** [wgenial/fipe-json#5]
Bom dia. Você poderia criar uma planilha que puxe os valores FIPE a partir de uma listagem de marca, modelo e ano?
Meu e-mail é jibh.jibh@gmail.com

**Comment by giovanigenerali** [comment]
@ignaciob73 por favor, entre em contato pelo email contato@wgenial.com.br e informe mais detalhes para podermos te passar uma estimativa de custo.
